title: "THESHAKHESTUDIUM"
email: theshakhestudium@theshakhestudium.com
description: "Silent and against the current. Not to conquer, but to decode."
baseurl: ""
url: "https://github.com/TheShakhestudium"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "es"]
default_lang: "en"
exclude_from_localizations:
  - "assets"
  - "README.md"

data_dir: _data

