title: "THESHAKHESTUDIUM"
email: you@correo.com
description: "Silent and against the current. Not to conquer, but to decode."
baseurl: ""
url: "https://TU-USUARIO.github.io"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "es"]
default_lang: "en"
exclude_from_localizations:
  - "assets"
  - "README.md"

data_dir: _data
Add _config.yml
